import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/header/Header";
// import Sidenav from "./components/sidenav/Sidenav";
import Footer from "./components/footer/Footer";
import LoaderWrapper from "./LoaderWrapper";
import { SmoothScrollProvider } from "./smoothScrollProvider/SmoothScrollProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <SmoothScrollProvider /> */}
        <LoaderWrapper>
          <SmoothScrollProvider>
            <div className="relative particleEffect">
              <Header />
              {children}
              <Footer />
            </div>
          </SmoothScrollProvider>
        </LoaderWrapper>
      </body>
    </html>
  );
}
